CREATE TABLE PESSOA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    SETOR_ID INT,
    FOREIGN KEY (SETOR_ID) REFERENCES SETOR(ID)
);

INSERT INTO PESSOA (FIRST_NAME, LAST_NAME, SETOR_ID) values ('João', 'Paulo', 1);
INSERT INTO PESSOA (FIRST_NAME, LAST_NAME, SETOR_ID) values ('Ana', 'Maria', 2);
INSERT INTO PESSOA (FIRST_NAME, LAST_NAME, SETOR_ID) values ('Antonio', 'Silva', 3);
INSERT INTO PESSOA (FIRST_NAME, LAST_NAME, SETOR_ID) values ('Alex', 'Monteiro', 1);
INSERT INTO PESSOA (FIRST_NAME, LAST_NAME, SETOR_ID) values ('José', 'Morais', 2);
INSERT INTO PESSOA (FIRST_NAME, LAST_NAME, SETOR_ID) values ('Rodrigo', 'Tarso', 3);
INSERT INTO PESSOA (FIRST_NAME, LAST_NAME, SETOR_ID) values ('Vanessa', 'Silveira', 1);